Fix `apollo-server-errors` import for typescript projects using apollo4
confuser/graphql-constraint-directive pull request #243
Opened 2024-07-04 14:46 UTC by damienwebdev

2024-08-06 22:26 UTC, dsambugaro commented
@confuser , any chances of this getting a review soon?

2024-08-07 10:24 UTC, confuser requested changes
Thanks for putting in the time for these fixes. Can you please add `test-typescript` to run as part of the pipeline to ensure future changes don't create a breakage again?

2024-09-17 14:29 UTC, damienwebdev commented
@confuser I've added this.

2024-09-17 14:41 UTC, confuser approved these changes

2024-09-17 14:42 UTC, merged

2024-12-13 14:52 UTC, dsambugaro commented
@confuser, do you have any estimate on when the fix from this merged PR will be released?